### ISSUE TITLE
devs.Model should not define text colors inside the 'text' selector.

### ISSUE THREAD

**Issue by DavidDurman** [DavidDurman/joint#105]
As Travis pointed out correctly, the devs.Model should not have the color for all the texts inside it defined in the attrs for 'text' selector. This is because if one sets the color of the '.label' to a certain color, this will not be taken into account because it will be overwritten by the 'text' attrs. One can see this happening by going to http://jointjs.com/rappid, adding a devs.Model to the paper and changing color of the label in the inspector.

For the time being, a quick fix is the following:

```javascript
delete joint.shapes.devs.Atomic.prototype.defaults.attrs.text.fill;
```

**Comment by kumilingus** [comment]
Fixed in next release.
