### ISSUE TITLE
bug in core.js

### ISSUE THREAD

**Issue by leungwensen** [DavidDurman/joint#109]
https://github.com/DavidDurman/joint/blob/master/src/core.js#L958

it seems that there is an undefined 'd3' here.

**Comment by rafalt** [comment]
https://github.com/mbostock/d3/wiki/Formatting#d3_round

**Comment by leungwensen** [comment]
I know about d3js and its helper functions, but is d3js one of the dependencies of jointjs? Is it `necessary` to load d3js before I can use jointjs?

**Comment by DavidDurman** [comment]
No, d3 is definitely not a dependency of JointJS. It was a typo, a leftover from a ported function. Nicely spotted! This is fixed in commit 76c4bbc
