### ISSUE TITLE
Clean up all DOM elements/views in paper.remove()

### ISSUE THREAD

**Issue by DavidDurman** [DavidDurman/joint#110]
It would be desirable to clean up all DOM elements/views inside paper.remove(). If someone calls paper.remove(), it is unlikely he will ever need access to the SVG elements associated with cell views. More info on this can be found in the following JointJS forum thread: https://groups.google.com/forum/#!topic/jointjs/j9O3g9s5goI

**Comment by kumilingus** [comment]
Fixed in next release.
