### ISSUE TITLE
Joint with Node-Webkit: Paper not included in nodejs module

### ISSUE THREAD

**Issue by vaubrun13** [DavidDurman/joint#112]
Hi,
I'm currently working on a node-webkit app and wanted to use jointjs, using the nodejs module, but figured out i can't be because the module does not include the joint.dia.paper.js

Here what i do:
![capture d ecran de 2015-02-03 16 15 24](https://cloud.githubusercontent.com/assets/6413816/6022825/f7df8f4c-abbf-11e4-8a0e-2de0a9d361dc.png)

but it crashes because joint.dia.Paper is undefined.
Is there a way to work it out ? Maybe by editing the index.js of the nodejs module:

![capture d ecran de 2015-02-03 16 18 16](https://cloud.githubusercontent.com/assets/6413816/6022865/4a81e27c-abc0-11e4-99be-72eba29a3f07.png)

Thx

**Comment by marksyzm** [comment]
I second this notion. Just about to correct it with a fork - will link in a mo

**Comment by kumilingus** [comment]
Fixed in #135.
