### ISSUE TITLE
FromJSON problems

### ISSUE THREAD

**Issue by jcfiorenzano** [DavidDurman/joint#122]
I did the following:
I made a function called *saveScene* and other called *loadScene*

```
 saveScene: function()
 {
     this.prueba = graph.toJSON();
 }
```

and great in `prueba` there is a very pretty JSON, but when I did this:

```
 loadScene: function()
 {
     graph.fromJSON(this.prueba)
 }
```
the following message appear in my console:

**Uncaught Error: properties.markup is missing while the default render() implementation is used.**

This is a recurrent problem in google group. But the answer is make my own *fromJSON* function. I don't want to do my own function, this function are already defined by you, then tell me why don't work. In some post say that some elements are not defined, but how these is possible I only push a button called saved, and after I push a button called load, nothing change all elements are defined, then how is possible that message appear.

**Comment by kumilingus** [comment]
Hi Juan,

make sure that all your elements are defined in joint.shapes.yourNamespace.

I suggest to read this thread
https://groups.google.com/forum/#!topic/jointjs/juO8r3-BtpU.

Regards,
Roman

On 16 March 2015 at 05:59, Juan Carlos Fiorenzano <notifications@github.com>
wrote:

> I did the following:
> I made a function called *saveScene* and other called *loadScene*
>
>  saveScene: function()
>  {
>      this.prueba = graph.toJSON();
>  }
>
> and great in prueba there is a very pretty JSON, but when I did this:
>
>  loadScene: function()
>  {
>      graph.fromJSON(this.prueba)
>  }
>
> the following message appear in my console:
>
> *Uncaught Error: properties.markup is missing while the default render()
> implementation is used.*
>
> This is a recurrent problem in google group. But the answer is make my own
> *fromJSON* function. I don't want to do my own function, this function
> are already defined by you, then tell me why don't work. In some post say
> that some elements are not defined, but how these is possible I only push a
> button called saved, and after I push a button called load, nothing change
> all elements are defined, then how is possible that message appear.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/DavidDurman/joint/issues/122>.
>



-- 
Roman Brückner
CTO at client.io
+420 776 504 406
roman@client.io
