### ISSUE TITLE
using jointJS inside a module

### ISSUE THREAD

**Issue by mteichtahl** [DavidDurman/joint#128]
I am currently refactoring my jointJS code out of the main js code and into a module

I an exporting the following (with paper and graph module variables)

"create": function (graphTarget,options) {
    target = $(window.document.getElementById(graphTarget));

    if (graph === undefined)
      graph = new joint.dia.Graph();

    var defaultPaperOptions = {
      el: target,
      width: target.width(),
      graph: graph,
      interactive: true,
      gridSize: 1
    };
    options = _.extend(defaultPaperOptions, options);
    paper = new joint.dia.Paper(options);
    return this;
  }

However, I get the following JS errors - ore.js?v=1428907215:61030 Uncaught TypeError: Cannot read property '_listenId' of undefined'

This is occuring when new joint.dia.Paper(options) is being called

I have checked target which is

[div#schemaChart.text-center.ibox-content, context: div#schemaChart.text-center.ibox-content, jquery: "2.1.3", constructor: function, selector: "", toArray: function…]
0: div#schemaChart.text-center.ibox-content
context: div#schemaChart.text-center.ibox-content
length: 1
__proto__: jQuery[0]

Any guidance would be appreciated

**Comment by kumilingus** [comment]
Hi Marc,

the `graph` attribute should be called `model`.

var defaultPaperOptions = {  el: target, width: target.width(),
*model*: graph, interactive: true, gridSize: 1 };

Regards,

Roman


On 13 April 2015 at 08:45, Marc Teichtahl <notifications@github.com> wrote:

> I am currently refactoring my jointJS code out of the main js code and
> into a module
>
> I an exporting the following (with paper and graph module variables)
>
> "create": function (graphTarget,options) {
> target = $(window.document.getElementById(graphTarget));
>
> if (graph === undefined)
>   graph = new joint.dia.Graph();
>
> var defaultPaperOptions = {
>   el: target,
>   width: target.width(),
>   graph: graph,
>   interactive: true,
>   gridSize: 1
> };
> options = _.extend(defaultPaperOptions, options);
> paper = new joint.dia.Paper(options);
> return this;
>
> }
>
> However, I get the following JS errors - ore.js?v=1428907215:61030
> Uncaught TypeError: Cannot read property '_listenId' of undefined'
>
> This is occuring when new joint.dia.Paper(options) is being called
>
> I have checked target which is
>
> [div#schemaChart.text-center.ibox-content, context:
> div#schemaChart.text-center.ibox-content, jquery: "2.1.3", constructor:
> function, selector: "", toArray: function…]
> 0: div#schemaChart.text-center.ibox-content
> context: div#schemaChart.text-center.ibox-content
> length: 1
> *proto*: jQuery[0]
>
> Any guidance would be appreciated
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/DavidDurman/joint/issues/128>.
>



-- 
Roman Brückner
CTO at client.io
+420 776 504 406
roman@client.io

**Comment by mteichtahl** [comment]
Roman,

thank you. This did work

However, interestingly enough I now have the following issue.

See https://gist.github.com/mteichtahl/591aa36bb03b7ae23ff8 for the module code.

I am calling this module as below
```
   if (rbacDiagram === undefined) {
        rbacDiagram = diagram.create('schemaChart');
      }

      if (rbacPaper === undefined) {
        rbacPaper = rbacDiagram.paper({interactive: false});
      }

  rbacDiagram
        .buildGraphFromAdjacencyList(data)
        .addCells()
        .layout();

```

The first time this is called, everything works well. However, subsequent calls (with a different adjacency list) result in a

```
Uncaught TypeError: Cannot read property 'el' of undefined
```

Which happens on

```
var magnetElement = view.el.querySelector(selector);
```

The code in gist, when transposed out of the module, works fine.

Im hoping you may be able to shed some light on this ?

**Comment by mteichtahl** [comment]
Any advice would be helpful

**Comment by kumilingus** [comment]
Hi Mark,

this error can occur when a link points (via source or target) to an
element which is not part of the graph (or there is no view rendered on the
paper for this element).
You saying the code works fine when is transposed out of the module, so I
expect the error is not related to an inconsistent adjacency list.

Could you send me an example that I can run and debug?

Cheers,
Roman

On 13 April 2015 at 23:53, Marc Teichtahl <notifications@github.com> wrote:

> Any advice would be helpful
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/DavidDurman/joint/issues/128#issuecomment-92511542>.
>



-- 
Roman Brückner
CTO at client.io
+420 776 504 406
roman@client.io

**Comment by mteichtahl** [comment]
Romance
A copy of the adjacency list? 






On Tue, Apr 14, 2015 at 3:44 AM -0700, "Roman Bruckner" <notifications@github.com> wrote:










Hi Mark,



this error can occur when a link points (via source or target) to an

element which is not part of the graph (or there is no view rendered on the

paper for this element).

You saying the code works fine when is transposed out of the module, so I

expect the error is not related to an inconsistent adjacency list.



Could you send me an example that I can run and debug?



Cheers,

Roman



On 13 April 2015 at 23:53, Marc Teichtahl <notifications@github.com> wrote:



> Any advice would be helpful

>

> —

> Reply to this email directly or view it on GitHub

> <https://github.com/DavidDurman/joint/issues/128#issuecomment-92511542>.

>







-- 

Roman Brückner

CTO at client.io

+420 776 504 406

roman@client.io

**Comment by kumilingus** [comment]
I mean a working example of the app (html + js) that I can run in browser
and see where it fails. Cheers.

On 14 April 2015 at 14:13, Marc Teichtahl <notifications@github.com> wrote:

> Romance
> A copy of the adjacency list?
>
>
>
>
>
>
> On Tue, Apr 14, 2015 at 3:44 AM -0700, "Roman Bruckner" <
> notifications@github.com> wrote:
>
>
>
>
>
>
>
>
>
>
> Hi Mark,
>
>
>
> this error can occur when a link points (via source or target) to an
>
> element which is not part of the graph (or there is no view rendered on the
>
> paper for this element).
>
> You saying the code works fine when is transposed out of the module, so I
>
> expect the error is not related to an inconsistent adjacency list.
>
>
>
> Could you send me an example that I can run and debug?
>
>
>
> Cheers,
>
> Roman
>
>
>
> On 13 April 2015 at 23:53, Marc Teichtahl <notifications@github.com>
> wrote:
>
>
>
> > Any advice would be helpful
>
> >
>
> > —
>
> > Reply to this email directly or view it on GitHub
>
> > <https://github.com/DavidDurman/joint/issues/128#issuecomment-92511542>.
>
> >
>
>
>
>
>
>
>
> --
>
> Roman Brückner
>
> CTO at client.io
>
> +420 776 504 406
>
> roman@client.io
>
>
>
>
>
> —
> Reply to this email directly or view it on GitHub.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/DavidDurman/joint/issues/128#issuecomment-92786478>.
>



-- 
Roman Brückner
CTO at client.io
+420 776 504 406
roman@client.io

**Comment by mteichtahl** [comment]
Romance
It's quite.a beast to share. I'd be happy to give you repo access or alternatively to find a suitable time and give you remote access to my development machine. Would either of those work for you?






On Tue, Apr 14, 2015 at 5:38 AM -0700, "Roman Bruckner" <notifications@github.com> wrote:










I mean a working example of the app (html + js) that I can run in browser

and see where it fails. Cheers.



On 14 April 2015 at 14:13, Marc Teichtahl <notifications@github.com> wrote:



> Romance

> A copy of the adjacency list?

>

>

>

>

>

>

> On Tue, Apr 14, 2015 at 3:44 AM -0700, "Roman Bruckner" <

> notifications@github.com> wrote:

>

>

>

>

>

>

>

>

>

>

> Hi Mark,

>

>

>

> this error can occur when a link points (via source or target) to an

>

> element which is not part of the graph (or there is no view rendered on the

>

> paper for this element).

>

> You saying the code works fine when is transposed out of the module, so I

>

> expect the error is not related to an inconsistent adjacency list.

>

>

>

> Could you send me an example that I can run and debug?

>

>

>

> Cheers,

>

> Roman

>

>

>

> On 13 April 2015 at 23:53, Marc Teichtahl <notifications@github.com>

> wrote:

>

>

>

> > Any advice would be helpful

>

> >

>

> > —

>

> > Reply to this email directly or view it on GitHub

>

> > <https://github.com/DavidDurman/joint/issues/128#issuecomment-92511542>.

>

> >

>

>

>

>

>

>

>

> --

>

> Roman Brückner

>

> CTO at client.io

>

> +420 776 504 406

>

> roman@client.io

>

>

>

>

>

> —

> Reply to this email directly or view it on GitHub.

>

> —

> Reply to this email directly or view it on GitHub

> <https://github.com/DavidDurman/joint/issues/128#issuecomment-92786478>.

>







-- 

Roman Brückner

CTO at client.io

+420 776 504 406

roman@client.io

**Comment by kumilingus** [comment]
@mteichtahl an access to your repo will do I guess.

**Comment by mteichtahl** [comment]
Roman
I have added you to my repo






On Tue, Apr 14, 2015 at 6:17 AM -0700, "Roman Bruckner" <notifications@github.com> wrote:












@mteichtahl an access to your repo will do I guess.

**Comment by kumilingus** [comment]
Thx Marc, I'll have a look.

**Comment by mteichtahl** [comment]
Roman

you will need to go to site/login. Please use admin@foo.com / admin as the username and password then go to administration->authentication

if you have vagrant, simply run vagrant up and a working VM on 192.168.99.2 will come up

you will need to run grunt install build

**Comment by mteichtahl** [comment]
Roman

Im available if you need assistance getting this running or using a remote desktop to my dev platform


-----------------------------------------------
Marc Teichtahl
marc@teichtahl.com
Ph: +61 434 100 259
http://www.teichtahl.com

**Comment by kumilingus** [comment]
Hi Mark,
I'm actually having problems to get it running (`vagrant up` spits out an error with funny characters `T␤␊ SSH ␌⎺└└▒┼␍ ⎼␊⎽⎻⎺┼␍␊␍ ┬␋├␤ ▒ ┼⎺┼-≥␊⎼⎺ ␊│␋├ ⎽├▒├┤⎽.`). Could you make your server available via `ngrok` and send me an url to roman@client.io?

**Comment by mteichtahl** [comment]
Will do shortly






On Wed, Apr 15, 2015 at 5:10 AM -0700, "Roman Bruckner" <notifications@github.com> wrote:












Hi Mark,

I'm actually having problems to get it running (vagrant up spits out an error with funny characters T␤␊ SSH ␌⎺└└▒┼␍ ⎼␊⎽⎻⎺┼␍␊␍ ┬␋├␤ ▒ ┼⎺┼-≥␊⎼⎺ ␊│␋├ ⎽├▒├┤⎽.). Could you make your server available via ngrok and send me an url to roman@client.io?
