### ISSUE TITLE
Link Tools Issue

### ISSUE THREAD

**Issue by JoseGoncalves** [DavidDurman/joint#86]
In my app I have a problem accessing to link options.
Using orthogonal routing, with several links being sourced by one shape, I can only access the 'Link options' and 'Remove link' tools for the link with the higher z attribute (see screenshot attached).
![screenshot](https://cloud.githubusercontent.com/assets/3037740/3566079/9ce99eac-0ae3-11e4-8b0c-aa5fcd7d5b7e.png)

**Comment by DavidDurman** [comment]
Fixed in Rappid v1.5 (and the associated JointJS version)
